### ISSUE TITLE
Better Diffie-Hellman Parameter APIs

### ISSUE THREAD

**Issue by hynek** [pyca/pyopenssl#11]
Currently there’s only one API for DH parameters that both loads and sets them on a context (`Context.load_tmp_dh`).

There should be APIs to do these steps _separately_: i.e. load into memory and set on an context.

**Comment by evilaliv3** [comment]
I agree on this topic.

In addition it would be really important to export an API to allow to inizialize the DH object by using a string.
This is a requirement in order to be able to create and use DH parameters in RAM without using the file system or eventually to use parameters stored in a different way (e.g. with a DB).

Right now this is not possible and the user in order to load a parameter has forcefully to create a file and load from it.

The following code could be used as reference, and uses tempfile that allow to create temportary files

```
import tempfile

def load_dh_from_string(ctx, dhparam):
    # self is a context object
    temp = tempfile.NamedTemporaryFile()
    temp.write(self.dh)
    temp.flush()
    ctx.load_tmp_dh(temp.name)
    temp.close()
```

**Comment by alex** [comment]
FFDH is bad and we're trying hard not to extend our APIs anyways.
