### ISSUE TITLE
Once cryptography minimal version is 41, do some relevant cleanup

### ISSUE THREAD

**Issue by itamarst** [pyca/pyopenssl#1206]
Follow-up to https://github.com/pyca/pyopenssl/pull/1202: 

Once cryptography v40 is no longer supported, `OpenSSL.SSL` can expose `X509_V_*` constants unconditionally.

**Comment by h-vetinari** [comment]
This has actually become relevant now that cryptography 41.0.0 has been released, and is (nominally?) incompatible with the metadata in this package, which forces the constraint solver (of conda) into weird [contortions](https://github.com/conda-forge/pyopenssl-feedstock/issues/30) that end up picking a very old pyopenssl that's not compatible with OpenSSL 3 for example.

Could we have a new release for pyopenssl, or alternatively, is it safe to remove the `<41` cap in the dependency metadata?

CC @alex @reaperhulk @hmaarrfk

**Comment by reaperhulk** [comment]
We're doing a release that raises the cap momentarily (a later release will raise the minimum).

**Comment by h-vetinari** [comment]
Thanks, that's great to hear!

(I realised too late that this issue was for once the _minimum_ is 41.x, sorry)

**Comment by facutuesca** [comment]
This issue was created at a point where the linked PR (https://github.com/pyca/pyopenssl/pull/1202) conditionally exposed the `x509_V_*` constants according to the available capabilities. However, before merge that conditional ended up being removed ([source](https://github.com/pyca/pyopenssl/pull/1202/commits/acb57ee15eac1d38ab0d69205df340707a62d943)). The reason for that was that the problematic `cryptography` versions that required that conditional were blacklisted in [`setup.py`](https://github.com/pyca/pyopenssl/pull/1202/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R101-R102), so the conditional was no longer needed.

So this issue is already fixed (the constants are already exposed unconditionally). And the `setup.py` blacklisting was already removed since the minimum `cryptography` version is already at `41.0.0` 

cc @mhils @reaperhulk
