### ISSUE TITLE
X509Name objects cannot have multiple (DC) attributes in DN

### ISSUE THREAD

**Issue by kimvais** [pyca/pyopenssl#165]
Because of this it seems to be impossible to create a 'AD-like' certificate e.g.
"CN=kimvais,OU=Users,DC=ad,DC=example,DC=com" as the DN components are stored as attributes.

IMO the whole **setattr** implementation of this is a bit funny way of doing this...

I'll figure out a way to fix this and submit a pull request, but before that I would like some input on what do you think would be a nice API for this?

**Comment by thanatos** [comment]
This is something I'd like as well. I'm not familiar with the API, sadly, but it can definitely be done with the command line. For example,

```
% openssl req -new -nodes -subj '/C=US/ST=CA/L=San Francisco/O=Company/OU=Large group/OU=Smaller group/CN=example.com' -out foo.csr
Generating a 1024 bit RSA private key
...........++++++
............++++++
writing new private key to 'privkey.pem'
-----
% openssl req -in foo.csr -noout -text
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: C=US, ST=CA, L=San Francisco, O=Company, OU=Large group, OU=Smaller group, CN=example.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (1024 bit)
                Modulus (1024 bit):
                    00:d3:bf:51:49:96:0c:45:6e:21:e1:68:e8:9d:7d:
                    bd:8c:fd:7c:83:13:28:b8:fb:4e:44:ee:f7:c7:08:
                    6c:79:65:f7:2d:d6:e5:40:8c:2d:0d:12:63:6c:b7:
                    ff:00:75:e9:3c:5f:d0:5d:79:17:53:1c:8d:53:31:
                    d8:a4:d4:7b:3c:e1:8c:73:01:cf:f9:d7:73:12:de:
                    e1:c0:3b:d9:c3:14:10:41:b9:b9:65:e5:46:34:07:
                    37:00:64:6d:26:cd:0f:ec:6b:36:ca:69:d9:fe:46:
                    ac:bb:0d:e5:2c:a8:02:df:67:57:85:df:2a:6f:8d:
                    19:69:e6:6e:be:d1:4a:68:a1
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00
    Signature Algorithm: sha1WithRSAEncryption
        59:44:64:d3:3e:1d:df:d5:cf:d8:e6:7d:84:31:8e:8f:0a:f1:
        d0:dd:8c:76:54:c9:e5:7f:52:75:b2:c2:8c:8a:ba:01:57:58:
        c4:b8:bb:c8:08:2d:ba:6a:2d:48:9e:84:ab:c8:df:96:7a:73:
        3b:02:dd:1c:40:87:3b:b9:08:69:d0:76:e0:18:da:75:e1:67:
        77:ce:65:80:b6:91:04:7d:78:1e:a6:02:60:42:d7:99:d2:64:
        af:b0:d8:bc:43:a9:13:f7:6c:df:c1:2b:24:76:2d:8c:c9:06:
        a2:e3:dd:86:5c:74:55:07:af:95:bf:74:b9:ec:20:d4:ff:dd:
        d5:6c
```

(I'm trying to simplify a script that does this; currently, it shells out to `openssl`, but I'd like to move to `pyopenssl`, since I think that'll be simpler, and allow me to skip an intermediate output file or two.)

**Comment by Crapworks** [comment]
Sorry to dig out this old topic, but I currently have the same problem. I want to create a certificate with multiple Organizations. I actually found out that you are explicitly deleting NIDs that are already set: 

https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/crypto.py#L520-L528

If I comment out this block, it is perfectly possible to create a Request with multiple Organizations, OrganizationalUnits, etc. Is there a particular reason why you have implemented this "cleanup"? Because I really don't like the idea of providing my "patched" version of pyopenssl bundled with my tool.

**Comment by exarkun** [comment]
I expect someone thought that NIDs had to be unique.  Maybe some do?  I don't really know.  Do you?

**Comment by reaperhulk** [comment]
NIDs definitely don't have to be unique in a subject. Things like multiple common names in certificates validated by browsers would definitely be playing with fire, but that's still a validation behavior as multiple CNs are allowed by the letter of X509.

That said, I'd suggest just using pyca/cryptography for generating certificates of this type. It's a dependency of pyOpenSSL anyway and has a much better API for this.

**Comment by Crapworks** [comment]
I just had a look at pyca/cryptography. Wasn't even aware of that! Looks awesome and exactly like what I am looking for. I am going to play around with that, thanks!

**Comment by alex** [comment]
https://cryptography.io/ should be used for any ongoing x.509 work, the pyOpenSSL x.509 is bad top-to-bottom.
