### ISSUE TITLE
X509StoreContext should accept CRLs

### ISSUE THREAD

**Issue by bgaifullin** [pyca/pyopenssl#256]
Now, there is no possibility to use CRLS with verify_certificate method

**Comment by sholsapp** [comment]
Hey @bgaifullin, you're right, it should. It also should accept quite a few other options, too. I talked about this a little bit in https://github.com/pyca/pyopenssl/pull/155#discussion_r24637816 which is the original commit that added the `verify_certificate` method.

As a stop gap while we make these changes, you can take an approach similar to that of @mrjefftang in https://github.com/pyca/pyopenssl/pull/155#discussion_r24635378 to implement the missing functionality directly in your client code.

I'll get to this soon, sorry!

**Comment by tisdall** [comment]
I was trying to add CRL to my twisted project and found this issue...  I'm surprised this hasn't been more of an issue.  There's code to make CRL objects and Revoked objects, but what can you do with those if you can't use them to verify a certificate?

**Comment by carletes** [comment]
While this gets implemented I'm doing something like this:

```python
from OpenSSL import crypto

def verify(ca_cert_pem, crl_pem, cert_pem):
    store = crypto.X509Store()
    store.add_cert(crypto.load_certificate(crypto.FILETYPE_PEM, ca_cert_pem))
    cert = crypto.load_certificate(crypto.FILETYPE_PEM, cert_pem)
    ctx = crypto.X509StoreContext(store, cert)
    ctx.verify_certificate()

    # Until `X509StoreContext` accepts CRLs
    crl = crypto.load_crl(crypto.FILETYPE_PEM, crl_pem)
    revoked = crl.get_revoked() or []
    for r in revoked:
        r_serial = r.get_serial()
        c_serial = "%X" % (cert.get_serial_number(),)
        if r_serial == c_serial:
            raise Exception("Certificate revoked")
```

**Comment by schlenk** [comment]
Currently you can do nearly nothing with CRL objects. You can manually compare the get_revoked() results (in the contorted way seen above by @carletes ) with the serial number of the cert.
But the recent cryptography 0.9 added the needed low level APIs to access a few more things in those objects and to add them to a verify stack.

**Comment by sholsapp** [comment]
@schlenk is anyone working on using these low level APIs to enhance the CRL objects? After taking a peek at this to get started, I realized as you pointed out that you can do nearly nothing with the CRL objects. I think at a minimum we need a way to get a handle on a X509 object that represents the revoked certificate.

@carletes that suggestion works, but isn't great because it depends on comparing serial numbers, which aren't guaranteed to be unique. To be correct, we need to cryptographically verify the bits in the certificate.

**Comment by schlenk** [comment]
@sholsapp A CRL does not have any idea what X509 object it refers to. It just states things about serial numbers and issuers, so the serial number and issuer pair should better be unique or you are in trouble. What is missing in @carletes code is decoding and checking the issuer name (or the certificate issuer extension, if CRL issuer and cert issuers are different). And checking the CRLs signature of course.

There are some efforts underway in the pyca/cryptography project to add more APIs to CRL objects, but not done yet.

**Comment by sholsapp** [comment]
@schlenk 

> A CRL does not have any idea what X509 object it refers to.  It just states things about serial numbers and issuers, so the serial number and issuer pair should better be unique or you are in trouble. 

Am I correct in assuming this is a statement about the current state of pyOpenSSL? Or are you saying this is how CRL are used in general.

I think this needs to be fixed.

Comparing a signature and issuer name isn't good enough because those values aren't guaranteed to be unique. That's why I say @carletes implementaiton isn't great. I think that we need to *add* the mapping between CRL and X509 object, otherwise there is no good way to *use* a CRL. Once we add the mapping between CRL and X509 object, we can cryptographically verify that the certificate that is being described in the CRL. I think it might even make implementing @bgaifullin original ask easier.

Thoughts on that? Maybe I'm confused about how CRL work... I admittedly don't use them very often. :smile:

**Comment by sholsapp** [comment]
Regarding this comment, I think it's probably worth linking in https://github.com/pyca/pyopenssl/pull/264.

> Comparing a signature and issuer name isn't good enough because those values aren't guaranteed to be unique.

This PR is still substantially better than what we have now, but still not bullet proof. @carletes any thoughts/comments? Do you have the cryptography API in place to get an X509 object from the CRL instead of just the subject name?

**Comment by sholsapp** [comment]
Heh, so in fact, I apparently don't understand how CRL works.

After some more reading, it seems that the CRL is just a list of serial number -- not the certificates themselves -- which are signed by the CA to prevent tampering. So, no cryptographic mapping of the certificate being described in the CRL to the certificate itself is possible... you just have to trust the CA that signed the CRL and hope they didn't goof up the serial number and issuer name. Seems broken to me, but oh well. :smile:

Sorry for the noise.

**Comment by alex** [comment]
Fixed
