### ISSUE TITLE
Outdated docs at https://pythonhosted.org/pyOpenSSL/

### ISSUE THREAD

**Issue by hynek** [pyca/pyopenssl#271]
We should nuke it and put a link/redirect to RTFD there.  Currently if I google for pyOpenSSL, our up to date docs don’t appear on the first page at all.

@exarkun @dstufft any idea how to do that?

**Comment by exarkun** [comment]
I don't know what pythonhosted.org is

**Comment by hynek** [comment]
That’s some PSF infra that was used before RTD came around.  Supposedly also automatically built stuff or something?  Since it carries 0.14, I thought you may be at least vaguely familiar with it. :)

It might have had a different name before and was renamed to protect against some JS-shenanigans.

Maybe @coderanger can help?  I don’t know any other people on the infra team other than that. :(

**Comment by dstufft** [comment]
It used to be called packages.python.org, we moved it to pyhonhosted.org because giving people the ability to arbitrarily upload anything they want to a python.org domain isn't a great idea.

Currently all you can do is upload new versions, you can't delete or redirect. I'll be making that happen in the near future though.

**Comment by hynek** [comment]
Can you point me to some docs?  I can upload something I guess.

**Comment by dstufft** [comment]
``python setup.py upload_docs`` or something like that. I'm not sure if there are docs for it. It's a setuptools command, takes a directory of HTML and uploads it.

**Comment by hynek** [comment]
Thank you for your help.  I have uploaded a redirect.
