### ISSUE TITLE
Getting around key size restrictions

### ISSUE THREAD

**Issue by korovamilkbar** [pyca/pyopenssl#390]
Hi,

Trying:
```
key = crypto.PKey()
key.generate_key(crpto.TYPE_RSA, 16)
```
causes the error `Error: [('rsa routines', 'RSA_BUILTIN_KEYGEN', 'key size too small')].

I understand that is this put in as a security measure, I want to try smaller keys in order to get a better understanding of how secure RSA is (not for any encryption). Is there anyone out there who is familiar enough with OpenSSL who can help me get around this restriction?

Thanks a bunch!

**Comment by reaperhulk** [comment]
OpenSSL doesn't set a lower bound on key sizes for security reasons, it sets it because the prime generation can get "stuck" generating the same prime values repeatedly when you bound the bit size so severely. If the same prime is generated 3 times it fails with that message.

Simply raise the bit length to 31 or so and you'll usually succeed. 31-bit moduli are trivially factorable as well (the current recommended minimum size is 2048).

**Comment by korovamilkbar** [comment]
@reaperhulk Thanks!
