### ISSUE TITLE
UserWarning: 'point_conversion_form_t' has no values explicitly defined

### ISSUE THREAD

**Issue by dobesv** [pyca/pyopenssl#392]
Seeing this warning when importing OpenSSL.  I think this 

    >>> import OpenSSL
    .../cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())

This probably needs to be addressed before updating to the "next version" of cffi.

    $ pip freeze | grep -i 'openssl\|ffi'
    cffi==1.3.1
    pyOpenSSL==0.15.1

**Comment by Lukasa** [comment]
@reaperhulk This is strictly about cryptography, I think. Specifically, it seems like CFFI doesn't like this (from `ec.py`):

```
typedef enum { ... } point_conversion_form_t;
```

The integer type of the enum members is implementation defined, annoyingly, so we may just have to put the entire enum into the `ec.py` file in order to get the CFFI to work it out.
