### ISSUE TITLE
Impossibility to save in PEM format DH parameters generated at runtime

### ISSUE THREAD

**Issue by evilaliv3** [pyca/pyopenssl#401]
Working on [Tor2web](https://github.com/globaleaks/Tor2web/issues/260), I tried to implement automagic generation of DH parameters at the first run of an SSL server.

i succeed in the generation of the key using OpenSSL._util.lib.DH_generate_parameters_ex but i'm not able to use any of the openSSL function for writing the generated parameters to a file.

the implemented code is:
```python
import os
from OpenSSL._util import (ffi as _ffi,
                                   lib as _lib)

dhfile = "./a.pem"
if not os.path.isfile(dhfile):
    dh = _lib.DH_new()
    _lib.DH_generate_parameters_ex(dh, 2048, 2L, _ffi.NULL)
    _lib.PEM_write_DHparams(dhfile, dh)
```

the error that i get running this is: 
```AttributeError: 'module' object has no attribute 'PEM_write_DHparams'```

the same happen if i try to use PEM_write_bio_DHparams

i wonder why this cuntions are not reachable, do you have any hint?

**Comment by reaperhulk** [comment]
The only functions available on the `lib` object are the ones that have been explicitly bound in pyca/cryptography (see: https://github.com/pyca/cryptography/tree/master/src/_cffi_src/openssl). `PEM_write_DHparams` and `PEM_write_bio_DHparams` are not currently bound, so that's why you're getting that error. If you'd like them to be available you'll need to submit a PR against that project to add them (`PEM_write_bio_DHparams` would be a reasonable binding to add, but we'd probably prefer to avoid `PEM_write_DHparams`).

**Comment by reaperhulk** [comment]
Closing since this is more properly a cryptography issue and not pyopenssl.
