### ISSUE TITLE
Is the pyopenssl thread-safe?

### ISSUE THREAD

**Issue by user0007** [pyca/pyopenssl#424]
Hello,

I'm wondering if I can use pyopenssl in a web environment (multithread) to generate RSA keys:

    key = crypto.PKey()
    key.generate_key(crypto.TYPE_RSA, 2048)
    priv_key = crypto.dump_privatekey(crypto.FILETYPE_PEM, key)

**Comment by reaperhulk** [comment]
pyopenssl uses cryptography, which registers thread locking callbacks with OpenSSL. These locking callbacks can be ill-behaved in subinterpreter (e.g. mod_wsgi environments that do not set `WSGIApplicationGroup %{GLOBAL}` but are otherwise reliable. So the short answer is: yes you should be able to use it in a multithreaded execution context, but if you're running under mod_wsgi you may need to alter some configuration.
