### ISSUE TITLE
crypto.load_privatekey raises an crypto.Error without any details

### ISSUE THREAD

**Issue by adiroiban** [pyca/pyopenssl#456]
In 0.13 crypto.load_privatekey is raising a crypo.Error which provides some details about the error.

In master the error is empty.

Here are the updated tests 

https://github.com/chevah/pyopenssl/commit/4115b5f04ead708bc34d25324c60f6994e011f39

I found those details very useful for auditing/logging problems in production.

Thanks!

**Comment by hynek** [comment]
Is this something that changed in 0.14 or 16.0?

**Comment by adiroiban** [comment]
This defect was introduced in 0.14.

I ran my test on 0.14, 0.15 and 16.0.0 and it fails

The problem is that when `_raise_current_error` is called from load_privatekey  `lib.ERR_get_error()` returns 0 ... might be an issue in python cryptography

Thanks!

**Comment by topnotcher** [comment]
`lib.ERR_get_error()` returns `0` because all the errors have already been read from the queue by `helper.raise_if_problem()`.

crypto.py:
```python
    if type == FILETYPE_PEM:
        evp_pkey = _lib.PEM_read_bio_PrivateKey(
            bio, _ffi.NULL, helper.callback, helper.callback_args)
        helper.raise_if_problem()  # This eats all the errors.
...
    if evp_pkey == _ffi.NULL:
        _raise_current_error()   # This raises an empty exception
```

When `helper.raise_if_problem()` does not raise an exception (i.e. there was no exception caught while calling `helper._read_passphrase()`) and `evp_pkey` is `NULL`, `exception_from_error_queue()` is called a second time (the first time being in `helper.raise_if_problem()`), and `lib.ERR_get_error()` returns `0` because all errors have already been retreived.
