### ISSUE TITLE
WantReadError occured while doing ssl connect

### ISSUE THREAD

**Issue by BingoZ** [pyca/pyopenssl#459]
```
import socket
from OpenSSL.SSL import *
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout((5) 
sock.connect(('xxx', 443))
ssl_sock = Connection(context, sock)
ssl_sock.set_connect_state()
ssl_sock.do_handshake()
```

I got WantReadError while running codes blew, but I found it runs ok if I delete 'sock.settimeout(5)'.

Could it be avoided?

**Comment by Lukasa** [comment]
Can you provide the full traceback please?

**Comment by Lukasa** [comment]
Also, are you sure your code is right? There appears to be an unclosed parenthesis in `sock.settimeout`.

**Comment by BingoZ** [comment]
import socket
# import OpenSSL
from OpenSSL import SSL
from OpenSSL.crypto import load_certificate, dump_certificate, FILETYPE_PEM, FILETYPE_TEXT

ip = '184.27.71.68'
port = 443
```

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((ip, port))
sock.settimeout(4)

context = SSL.Context(SSL.SSLv23_METHOD)
context.set_verify(SSL.VERIFY_NONE, lambda c,x,en,ed,ok: True)
ssl_con = SSL.Connection(context, sock)
ssl_con.set_connect_state()
ssl_con.do_handshake()
```

**Comment by BingoZ** [comment]
Blew is my code ，you can run it locally

**Comment by BingoZ** [comment]
If you delete 'sock.settimeout(4)', it will runs ok.

**Comment by BingoZ** [comment]
Do you still need traceback now?

**Comment by Lukasa** [comment]
No, I have the traceback here:

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    ssl_con.do_handshake()
  File "/Users/cory/tmp/env/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1443, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/cory/tmp/env/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1167, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
```

So, the problem here is a confusion of the relationship between connections and sockets in Python. When a timeout is set on a Python socket, it switches into a non-blocking mode and Python uses `select` to emulate the timeout behaviour. This means that the difference in the two cases is that the second you choose `settimeout` the socket is swapped into a non-blocking mode. In that mode, OpenSSL cannot block on the read: there is no data yet to read.

If you are determined to use socket timeouts, you need to be prepared to catch these errors. You can see [urllib3 handle this problem here](https://github.com/shazow/urllib3/blob/master/urllib3/contrib/pyopenssl.py#L205-L211).

**Comment by BingoZ** [comment]
Got it. Thank you a lot.
