### ISSUE TITLE
Wrong order of data in Subject in PEM_TYPE CSR

### ISSUE THREAD

**Issue by jpaulovic** [pyca/pyopenssl#467]
[pyOpenSSL_bugreport.zip](https://github.com/pyca/pyopenssl/files/240258/pyOpenSSL_bugreport.zip)
When using the function crypto.dump_certificate_request(crypto.FILETYPE_PEM, req) the data in the property 'Subject' contained in the generated CSR are in wrong order.
The correct order if the Subject should be: CN, C, ST, L, O, OU/emailAddress; but the CSR contains it in this order: emailAddress = root@localhost,OU = DevOps,O = My Company,L = Brno,ST = Jihomoravsky,C = CZ,CN = test.example.com . 

The openssl 1.0.2.g-fips binary is intelligent enough to display it in the correct order, but when the CSR is decrypted programatically, the wrong order causes problems. The tool I used to check the Subject is here: https://certlogik.com/decoder/ . 

The aforementioned openssl binary version creates the CSR with a correct order of data in the Subject property. Please fix this so the library encodes the Subject fields in the correct order while generating PEM CSR file.

Attached are two CSRs, one correct, created by the openssl binary and one incorrect, created by the crypto module of the pyOpenSSL 0.15.1, which is the latest version available on Fedora Core 23.

Thanks.

**Comment by hynek** [comment]
I may be missing something but ISTM we’re just using OpenSSL’s function to dump CSRs: https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/crypto.py#L2501

Where exactly would I be looking for the definition of the correct order?

**Comment by jpaulovic** [comment]
The [RFC2459](https://tools.ietf.org/html/rfc5280#section-4.1.2.6) states that the Subject field is a "hierarchical name composed of attributes". If you look at the CSRs attached in my original post, the one created with openssl binary has the correct hierarchy of the Subject, the pyOpenSSL crypto one has the order wrong. I suppose this may be caused by the fact that Python stores the values in a data structure that doesn't guarantee the order of the values and when you just throw it at a function that encodes it to PEM, it doesn't reorder them to the correct order. I think You need to make sure the order is right before sending it to the encoder function.

Thanks.

**Comment by reaperhulk** [comment]
The code in question just appends to the end of an X509_NAME stack (with one nuance: it searches for an existing element and if it finds it, deletes it. This is actually wrong since multiple values are not necessarily incorrect but that's the API we've got here). Since the pyOpenSSL API doesn't implicitly reorder it is the caller's responsibility to generate the CSR in an ordered fashion. In this case the code to generate it in the expected order would need to look something like:

```
req = X509Req()
name = req.get_subject()
name.C = 'CZ'
name.ST = ''
name.L = ''
name.O = ''
name.OU = ''
name.CN = ''
name.emailAddress = ''
```
In the incorrect file it appears it was called in this order: CN, C, ST, L, O, OU, emailAddress. 

I don't believe pyOpenSSL should do this by default but if you're interested in contributing it would potentially make sense to add a sort method to the X509Name object. Ideally this sorting would come from an OpenSSL function. If not, we have to think about what sorting looks like with arbitrary OIDs where the specificity is not known to the sorting algorithm.

BTW, in general we're beginning to encourage users of the non-TLS parts of pyOpenSSL to look closely at [pyca/cryptography](https://github.com/pyca/cryptography), as that's where the majority of development effort is going (and all of pyOpenSSL is built on top of that project).

**Comment by jpaulovic** [comment]
reaperhulk, thanks, that did the trick.
