### ISSUE TITLE
how to decode the  ASN.1 encoded data of X509 extension

### ISSUE THREAD

**Issue by 1163307648** [pyca/pyopenssl#696]
how to decode the  ASN.1 encoded data of X509 extension ?
for example, X509Extension(b'basicConstraints', True, b'CA:true'),get_data() return b'0\x03\x01\x01\xff'. how to transform b'0\x03\x01\x01\xff' to  b'CA:true'

**Comment by atusingh** [comment]
From https://tools.ietf.org/html/rfc5280#section-4.2.1.9
```
   BasicConstraints ::= SEQUENCE {
        cA                      BOOLEAN DEFAULT FALSE,
        pathLenConstraint       INTEGER (0..MAX) OPTIONAL }
```

So breaking your data:

First byte: 0 => 0x30 => This means [SEQUENCE](https://msdn.microsoft.com/en-us/library/windows/desktop/bb648645(v=vs.85).aspx)

Second byte: 0x03 => This means that the length of the data in this SEQUENCE is 3. Notice that that there are three bytes after this byte in you data.

Third byte: 0x01 => We are now inside the data of a SEQUENCE, so we must expect a TYPE tag. 0x01 is [BOOLEAN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb648639(v=vs.85).aspx). Also as per the x509 ASN1 schema above, since this is the first item in the SEQUENCE, the value of this data type must correspond to `cA`

Fourth byte: 0x01 => Length of data in BOOLEAN. Notice that there is one byte left.

Fifth byte: 0x01 => Value of `cA`

**Comment by schlenk** [comment]
Best way to do it is to use a proper ASN.1 parser, for example `pyasn1`. While the description of is right for your data, there can be a few variants in the encoding, e.g. different ways to encode the length for example. 

Maybe you want to use the https://cryptography.io/en/latest/x509/reference/#x-509-extensions code instead of the `pyopenssl` libs to handle this. You have typically it anyway, as it is a prerequisite for pyopenssl.

**Comment by alex** [comment]
Yes, cryptography.io is prefered for advanced x.509 handling.
