### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_up_ref'

### ISSUE THREAD

**Issue by jayvdb** [pyca/pyopenssl#728]
In the last few hours (6?), after the release of 17.5.0, @coala started seeing the following on our CI for a repo which doesnt have many pins in place. 

```
Starting new HTTP connection (1): docs.coala.io
From cffi callback <function _verify_callback at 0x7f097d2b89d8>:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
```

Our upstream issue is https://github.com/coala/corobo/issues/433 .  pinning to <17.5 solved the immediate problem, so we dont need anything.
Sorry I havent done more analysis at this point - we are participating in Google Code-in , and I am org admin, so getting builds going is as much as I have time for at the moment.
Feel free to close if this report isnt good enough; just trying to give you a heads up.

**Comment by alex** [comment]
What version of `cryptography` do you have installed in this environment?

**Comment by reaperhulk** [comment]
Looking at a CI build (https://semaphoreci.com/coala/corobo/branches/pull-request-428/builds/1) it appears you're pinned to `cryptography` 2.0.3, but the new `pyOpenSSL` requires 2.1.4 or greater. This isn't caught during install because `pip` doesn't have a particularly good dependency resolver (until the next version hopefully!). You'll need to upgrade your `cryptography` pin.

**Comment by jayvdb** [comment]
;-)

Thanks.

That is why I put the pyopenssl pin at the top of `requirements.txt` .  We dont have a pin on cryptography on that project, but we'll look at dependencies (some of the dependencies are own, so we're not in the clear yet).

**Comment by reaperhulk** [comment]
@jayvdb if it helps the pin was coming from `/opt/errbot/requirements.txt`

**Comment by reaperhulk** [comment]
`Collecting cryptography~=2.0.3 (from IGitt==0.4.1.dev20171129151739->-r /opt/errbot/requirements.txt (line 4))` (sorry, this will be more useful probably)

**Comment by gnomic** [comment]
Upgrading cryptography solved this issue for me, but made me aware of a larger issue. I'm seeing multiple versions of the same package installed by PIP and Conda - this started about the time one of the packages came off of conda-forge. In this case I have a pip installed cryptography v1.9 and a conda version at 2.4. Upgrading the 1.9 version with pip, now have a 2.4 version and 2.5 version. 

This doesn't end well.

Is there any simple way to clean this up?

**Comment by AnjaneyuluBatta505** [comment]
In my case, `pip uninstall pyOpenSSL` worked for me

**Comment by bgbrandongomez** [comment]
What's sad is, there are so many issues with the error `AttributeError: module 'lib' has no attribute 'X509_up_ref'` that I could not find this post until I looked at the source code and pasted the offending line into search.

Thanks for the post: https://github.com/pyca/pyopenssl/issues/728#issuecomment-390099034

I was finally able to upgrade cryptography and get certbot (the program I use that broke) working.

**Comment by Mincka** [comment]
> 
> 
> In my case, `pip uninstall pyOpenSSL` worked for me

In my case, I was unable to uninstall it on macOS (`operation not permitted`), however a reinstallation with brew fixed it.

However, it is now not so easy to reinstall Python@2 with brew anymore (because they removed it) but this solution worked and fixed everything:
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/86a44a0a552c673a05f11018459c9f5faae3becc/Formula/python@2.rb`

Source: https://stackoverflow.com/a/60345962/3049282
