### ISSUE TITLE
OCSP verification with HTTP URI

### ISSUE THREAD

**Issue by Ashex** [pyca/pyopenssl#780]
I'm working on implementing OCSP stapling verification and it's not clear how to validate certificates that provide http (non-ssl) URIs, such as http://ocsp.int-x3.letsencrypt.org

Forcing the verification to use HTTPS may work with some providers but not lets encrypt which returns a 504 when attempting to use HTTPS.

Any guidance on how to handle HTTP OCSP URIs with pyopenssl would be greatly appreciated.

**Comment by reaperhulk** [comment]
OCSP is not designed to be fetched over HTTPS because you end up in a circular verification loop. Instead, you validate the OCSP signature against the local root store to confirm that the payload is genuine. Verification of OCSP responses is not something pyOpenSSL supports at this time, but be aware that doing validation like that is extremely tricky.

**Comment by Ashex** [comment]
Thanks for the details, I was aware of the circular verification loop when going over HTTP. It's unfortunately that verfification isn't supported by pyOpenSSL, I've managed to implement a workaround using the openssl cli so I'll close this out.
