### ISSUE TITLE
pip install pyopenssl failed

### ISSUE THREAD

**Issue by nikhil-gofynd** [pyca/pyopenssl#869]
Step to repdoduce:
`pip install pyOpenSSL`

Error: `Running setup.py install for cffi error`.

Probably new release from cffi causing build failed for cffi dependency.

**Comment by alex** [comment]
You didn't provide enough information for us to debug this.

However I'd bet almost anything that your problem is that you can't build cffi because you don't have libffi or some other dependency, and there's a new cffi release today which doesn't yet have wheels.

Wheels for cffi will be up shortly, but in any event this isn't a pyopenssl bug.

**Comment by nikhil-gofynd** [comment]
`libffi-dev`
Got it. Thanks
