### ISSUE TITLE
How to create the 'certificate policies' extension in pyOpenSSL?

### ISSUE THREAD

**Issue by lsj9383** [pyca/pyopenssl#912]
When I use the code
```
crt.add_extensions([X509Extension(b'certificatePolicies ', False, b'2.5.29.32.0')])
```

raise a exception:

Traceback (most recent call last):
  File "x", line 138, in <module>
    main()
  File "x", line 123, in main
    crt.add_extensions([X509Extension(b'certificatePolicies ', False, b'2.5.29.32.0')])
  File "/usr/lib64/python2.7/site-packages/OpenSSL/crypto.py", line 764, in __init__
    _raise_current_error()
  File "/usr/lib64/python2.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('X509 V3 routines', 'do_ext_nconf', 'unknown extension name'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]

**Comment by reaperhulk** [comment]
You should use cryptography to generate X509 certificates (https://cryptography.io/en/latest/x509/reference/#x-509-certificate-builder) and not pyOpenSSL's bad APIs. pyOpenSSL expects exact values OpenSSL specifies and depends heavily on what version of OpenSSL you've linked against. For example, in my own environment it recognizes certificatePolicies, but fails because a bare OID is not a valid CP structure.
