### ISSUE TITLE
Invalid License, appears this project should be LGPL 2.1

### ISSUE THREAD

**Issue by michaelgugino** [pyca/pyopenssl#938]
I am not a lawyer, my understanding of software licensing is limited, this not legal advice.

At one point in time, the license of this project was changed from LGPL 2.1: https://github.com/pyca/pyopenssl/commit/e04fecc0c7a4125953d62002c895e429d8e4bb7e

This change appears to be unilateral, I've searched through the mailing list and found no explanation given for this change.  This library and all of its derivatives should be licensed under the LGPL.  The work cannot be re-licensed without the consent of the existing copyright holders (outside of the excepts listed in the license).  Seeing as the original entity appears defunct, I find it very unlikely that permission was indeed given.

Frankly, puts the commits between that time period and today into a precarious position, IMO.

**Comment by alex** [comment]
@exarkun can you chime in here? My guess is that this was because _all_ of the code was rewritten when you migrated from C to Python, and thus you were the sole copyright holder, but I don't know for sure.

If this whole project is incorrectly licensed, I suspect we'll just delete it.

**Comment by michaelgugino** [comment]
Here's some C code that exists well after that license change.  Note the copyright headers:

https://github.com/pyca/pyopenssl/blob/a9f84ad2c19b213dfb57fdaa5133658b0a4ff853/OpenSSL/util.c

Here's a commit that shows tsafe.py (which exists in initial source import) after removal of C code: https://github.com/pyca/pyopenssl/commit/f0e6685b0880bbc30099c998454925ee8d39b14e

At that point in time, there seemed to be a variety of contributors to the project.  Those contributors were distributed the project in a form that should have been covered by the LGPL, therefor, there contributions at that time should have been covered by the LGPL.

I think, an argument could be made that the code as it exists today is fundamentally a different implementation, but that implementation was arrived via series of derivative works.

The source was original licensed as LGPL 2.1+, which does allow for any later version according to the original license:
https://github.com/pyca/pyopenssl/blob/c0c64ef48cf68198b6ecf4c9bb60d664a9376709/README

Accordingly, the entire work could be licensed as GPL 3 (I'm unsure if Apache and LGPL licenses are compatible).

I think the licensing here is in somewhat of a grey area (which I think most people would also describe licensing in general).  I'm not sure what the right course of action is, but I'm leaning towards LGPL or GPL licensing.

**Comment by exarkun** [comment]
Oh, fun.

So, first, this was 9 years ago.  My memory is certainly fallible.  I don't swear this is all true but it's my best recollection at the moment.  If there are mistakes, they are unintentional and I apologize.

Right now, I believe that 2011 Jean-Paul Calderone had a sufficient understanding of copyright law that he would not just unilaterally re-license someone else's work.  This is not evidence that the current license is valid but it is sufficient cause for me to want to look for evidence that supports that conclusion.

The first place I looked is the place suggested by alex's comment above - the source itself.  It's true that the project was originally written completely in C and I rewrote it all in Python.  I (along with some other contributors) also wrote some portion of the C between 2008 (when I took over maintenance of the project) and 2014 (when the Python re-write was merged).  The test suite was also written from 2008 onward and all of the original API documentation was reformatted for Sphinx in 2011 though I believe much of the actual content remained the same.

The port to Python in 2014 doesn't seem to align well with a license change in 2011.  I don't believe I would have changed the license 3 years in advance of a significant rewrite - both because this would be invalid for the 3 interim years and I don't believe such a rewrite appeared feasible in 2011.

There is one alternative that just barely tickles my memory, which is that I may really have contacted all contributors as of 2011 and requested permission to re-license the project.  If this is the case, it was extremely poor form not to publish this permission where we, today, could find it.  Since that appears not to have been done (or at least it is not obvious where that publication happened), my own email archives or the email archives of another contributor at the time might be the best bet.  However, my archives for that period are either incomplete or they are scattered across more storage than I have ready access to.

I'm sure it would be an unreasonable undertaking to contact *all* of the then-contributors at this point but perhaps one or two of them are still active and would have more luck remembering what the story was or consulting their own archives.

**Comment by exarkun** [comment]
> Those contributors were distributed the project in a form that should have been covered by the LGPL, therefor, there contributions at that time should have been covered by the LGPL.

I am also not a lawyer.  This is not a legal opinion.  This is not actually how it works with LGPL, unfortunately.  It *is* how it works with the Apache license.  Without some kind of contributor agreement, there is no clear license for works contributed to an LGPL-licensed project.  There is "common practice" and such, of course, but what legal bearing that might have is unclear to me.

This is not to try to make a point supporting any particular conclusion, I just want to make sure any subsequent reasoning rests on a sound foundation.

**Comment by alex** [comment]
Looking at the BZR version of the repo, @exarkun indicates that he received consent of all contributors: https://bazaar.launchpad.net/~exarkun/pyopenssl/trunk/revision/141

**Comment by glyph** [comment]
Since the history was relatively cleanly migrated from bzr, we have this commit in Git as well — linking here for posterity in case Launchpad goes up in smoke at some point:

https://github.com/pyca/pyopenssl/commit/666733a28cf858af1907d5dae27f00cb675a77b7
