### ISSUE TITLE
How to dump certificate chain into PEM file using pyopenssl module in python

### ISSUE THREAD

**Issue by srinivasev** [pyca/pyopenssl#999]
I wanted to dump the complete certificate chain into PEM file. Currently, I am trying this with the OpenSSL module, as the ssl module doesn't give the methods to fetch the certificate chain(only server certificate download is available).

`import OpenSSL

def get_cert_chain(address, port=443):
context = Context(SSLv23_METHOD)
client = socket()
client.connect((address, port))
clientSSL = Connection(context, client)
clientSSL.set_connect_state()
clientSSL.do_handshake()
return clientSSL.get_peer_cert_chain()

#The below certificate_chain variable contains the stack of X509 certificates
certificate_chain = get_cert_chain('www.google.com')`

Purpose : I wanted to import full chain of target IP and run the keytool import over the .pem file for adding into Wildfly truststore. But, there are no methods in X509 class to perform operations like dump the chain into .pem file and something similar to it.

Added the screenshots below for the same - (debug point)

<img width="676" alt="certificate chain 1" src="https://user-images.githubusercontent.com/11441751/110274216-50d7cd80-7ff4-11eb-9aea-24e8b014b4e2.PNG">
<img width="678" alt="certificate chain 2" src="https://user-images.githubusercontent.com/11441751/110274220-5208fa80-7ff4-11eb-8789-ed3b3fa5fcb3.PNG">

**Comment by reaperhulk** [comment]
In general the pyOpenSSL (and cryptography) bug tracker is not a generic help forum. If you have issues in the future please consider posting to something like StackOverflow, which has more users who can help with general usage of tools like this. That said...

You've found [get_peer_cert_chain](https://www.pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.Connection.get_peer_cert_chain), but since it returns an [X509](https://www.pyopenssl.org/en/stable/api/crypto.html#x509-objects) instance you could either loop over them and call `to_cryptography` and use the [cryptography X509 serialization APIs](https://cryptography.io/en/latest/x509/reference.html#cryptography.x509.Certificate.public_bytes) or use [dump_certificate](https://www.pyopenssl.org/en/stable/api/crypto.html#OpenSSL.crypto.dump_certificate). Based on your comments it seems you may have just tried to look at the class itself rather than reading the available docs.

**Comment by srinivasev** [comment]
Hi @reaperhulk ,

Thanks for the comment, I added a code snippet that prints the complete chain of certificates below. Are you referring the same `to_cryptography` with serialization apis?.

`
[....other code]
certificate_chain  = clientSSL.get_peer_cert_chain()
for cert in certificate_chain:
        print(cert.get_issuer())
        print(cert.get_subject())
        pem_file = cert.to_cryptography().public_bytes(serialization.Encoding.PEM)
        print(pem_file)`
